### ISSUE TITLE
Maximize doesn't work with ADMM

### ISSUE THREAD

**Issue by tridao** [snap-stanford/snapvx#1]
Hi,

Looks like the Solve() function doesn't yet work with `useADMM=True` and `M=Maximize`. For example, the following snippet will result in an error:

```
from snapvx import *

gvx = TGraphVX()
x = Variable(name='x')
gvx.AddNode(1, x, [x <= 2])
gvx.Solve(M=Maximize, useADMM=True)
```

**Comment by davidhallac** [comment]
Hi Tri,

Thanks for pointing this out. This is something that we forgot to change from an older version. We realized that the maximize vs. minimize distinction should be on a node-by-node basis (and not a "general" parameter in the entire network). However, we decided for our initial release to only allow minimization. When using ADMM, you would have to minimize the negative of the objective, instead of maximizing the original objective. 

I will leave the "maximize" parameter for now, in case people need to use it for non-ADMM, but I will update the documentation to clarify when it can/can't be used.

Minimization/Maximization on a node-by-node and edge-by-edge basis is something we will work on incorporating into a future release of SnapVX.

Thanks again for noticing this,
David
