### ISSUE TITLE
Is Network-Enhanced Classification in Network Lasso paper implemented in snapvx?

### ISSUE THREAD

**Issue by DanqingZ** [snap-stanford/snapvx#25]

**Comment by davidhallac** [comment]
The code from that paper is available here (https://github.com/davidhallac/NetworkLasso). The network-enhanced classifier example is implemented in a very old version of SnapVX, but you can find it at "svm_paper.py" in the github repo. You could run that code directly, or it shouldn't be too bad to convert the example over to the newest version of SnapVX, since we can still handle those objectives/constraints.
