### ISSUE TITLE
Weighted lasso penalty on edges

### ISSUE THREAD

**Issue by ghost** [snap-stanford/snapvx#6]
I wanted to solve the problem in equation 2 in the paper (http://web.stanford.edu/~boyd/papers/pdf/network_lasso.pdf). I'm wondering how can I specify the weights w_ij in the code.

**Comment by davidhallac** [comment]
The easiest way to account for weights in this case would be to have a python dictionary of ( (srcID, dstID), weight ). Once you have this, you can define the edge weights as follows:

```
from snapvx import *

gvx = LoadEdgeList("mygraph.txt")

for node in gvx.Nodes():
    #Set node objectives here

for edge in gvx.Edges():
    src = edge.GetSrcNId()
    dst = edge.GetDstNId()
    weight = mydict.get((src,dst))
    obj = #Set edge objective here
    gvx.SetEdgeObjective(src, dst, weight*obj)

gvx.Solve()
gvx.PrintSolution()
```

**Comment by ghost** [comment]
Thanks. I followed the steps that you suggested but I'm still getting some
error in the last part of the code (Since src and dst are node IDs hence
integers, they don't have any attribute  '**getitem**')

my_data = genfromtxt('edges_weights.csv', delimiter=',')
weight_dict = {};
for i in range(my_data.shape[0]):
  srcID = int(my_data[i,0]);  desID = int(my_data[i,1]);
  weight = my_data[i,2];
  weight_dict[(srcID,desID)] = weight;

#Load in Edge List to build graph with default node/edge objectives
gvx = LoadEdgeList('edges_supervoxel.txt');

my_data = genfromtxt('superVoxelMeans.csv', delimiter=',');
for node in gvx.Nodes():
a = my_data[node.GetId()-1,];
x = Variable(my_data.shape[1],name='x');
gvx.SetNodeObjective(node.GetId(), square(norm(x-a)));

'''

> > > for edge in gvx.Edges():
> > > ...     src = edge.GetSrcNId();
> > > ...     dst = edge.GetDstNId();
> > > ...     weight = weight_dict[(src,dst)];
> > > ...     obj = norm(src['x'] - dst['x']);
> > > ...     gvx.SetEdgeObjective(src, dst, weight*obj);
> > > ...
> > > '''
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 5, in <module>
> > > TypeError: 'int' object has no attribute '**getitem**'

**Comment by davidhallac** [comment]
The src['x'] and dst['x'] syntax only works for when you define a new function for the edge objective and bulk load it (see BulkLoading.py in the examples folder) . To solve it your way, you just have have to change one line in your code. Switch "obj = norm(src['x'] - dst['x']);" to "obj = norm(gvx.GetNodeVariables(src)['x'] - gvx.GetNodeVariables(dst)['x'] ) ", and it should work

**Comment by ghost** [comment]
Thanks, this works. However it is taking too long to add the edge
objectives. Is there a way to bulk load the weighted edge objectives with
the weights given by weight_dict above?

**Comment by davidhallac** [comment]
Hmm, you know, I actually don't think there's an easy way to bulk load with edge weights in the current version of SnapVX. The issue is that AddEdgeObjectives takes a function with the src and dst nodes, but it only passes a dictionary of variables. It does not pass the NodeID, which you would need to solve for the edge weights.

This is something we will work on for the next release of SnapVX. Out of curiosity, how long does looping through and loading all the edges take?

**Comment by ghost** [comment]
Each edge objective takes about 0.6 secs to add, we have around 2M edges.

**Comment by davidhallac** [comment]
Hmm, to be totally honest, even with bulk loading, that might be a bit beyond what SnapVX is currently set up to solve...

Our solver typically works best on medium-sized graphs with complicated node/edge objectives, rather than on really large graphs where the objectives are easy (i.e. in R^1). One approach is to combine your nodes into "supernodes" with grouped objective functions and get a smaller graph, but unfortunately for now I don't have a definite solution for you. We're working on improving the scalability and functionality of our solver in cases like these. There is nothing imminent yet, but stay tuned!
